spring:
  application:
    # name of the application
    name: discovery-config-server
    # available profiles of the application
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          # git url where the configurations are stored
          uri: https://github.com/patidarvjy/centralized-configuration.git
          # if configurations are in sub folders search the subfolder by below name
          search-paths: discovery-server/
server:
  # config server port
  port: 8761
management:
  security:
    # disable security of the config server
    enabled: false
